version: '3'
services:
  db:
    image: percona:5.7
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: formn-example-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=formn-password
      - MYSQL_DATABASE=formn_test_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

